/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spades;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;

/**
 *
 * @author xps8900
 */
public class Scoreboard extends javax.swing.JPanel {
    
    private final int WINNING_SCORE = 500;
    
    private int team1Score;
    private int team2Score;
    
    private Bids b;
    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        initComponents();
        team1Score = 0;
        team2Score = 0;
        
        b = new Bids();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Bid");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!b.hasBid())
            b.bid();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.drawString("Team 1: " + team1Score,getWidth()/4, getHeight()/2);
        g2d.drawString("Team 2: " + team2Score,getWidth()/2, getHeight()/2);
        System.out.println("Yo");
    }
    
    /*
    This takes in the number of tricks one by each team in game and updates
    the scoreboard with regards to their bid. 
    */

    /**
     *
     * @param t1Trick
     * @param t2Trick
     */

    public void updateScore(int t1Trick, int t2Trick)
    {
        int t1Bid = b.team1Bid();
        int t2Bid = b.team2Bid();
        if(t1Bid <= t1Trick)
            team1Score += t1Bid*10 + (t1Trick-t1Bid);
        else
            team1Score -= t1Bid*10;
        if(t2Bid <= t2Trick)
            team2Score += t2Bid*10 + (t2Trick-t1Bid);
        else
            team2Score -= t2Bid*10;
        b = new Bids();
        if(t1Trick + t2Trick != 13)
            System.out.println("Thats not the 13 total number ot tricks won");
        showWinner();
        repaint();
    }
    /**
     * Sees if a team has won
     * @return the winning team or 0 if nobody has won
     */
    private int checkWinner()
    {
        if(team1Score > WINNING_SCORE && team1Score > team2Score)
            return 1;
        else if(team2Score > WINNING_SCORE && team1Score < team2Score)
            return 2;
        else
            return 0;
            
    }
    /**
     * Makes a message if a team has won
     */
    private void showWinner()
    {
        if(win())
            JOptionPane.showMessageDialog(null, "Congragulations to team " + checkWinner() + " You have won!!!");
        
    }
    
    /**
     * @return if a winner has been found
     */
    public boolean win()
    {
        return checkWinner() != 0;
    }
    
    /**
     * IF the bidding is finished
     * @return
     */
    public boolean doneBid()
    {
        return b.hasBid();
    }
    /**
     * Resets the scores for a new game
     */
    public void reset()
    {
        team1Score = 0;
        team2Score = 0;
        b = new Bids();
    }
    
            
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
