/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spades;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author xps8900
 */
public class Scoreboard extends javax.swing.JPanel {
    private int team1Score;
    private int team2Score;
    private boolean newGame;
    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        initComponents();
        team1Score = 0;
        team2Score = 0;
        newGame = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.drawString("Team 1: " + team1Score,getWidth()/4, getHeight()/2);
        g2d.drawString("Team 2: " + team2Score,getWidth()/2, getHeight()/2);
        System.out.println("Yo");
    }
    
    public void updateScore(int t1, int t2)
    {
        team1Score += t1;
        team2Score += t2;
        repaint();
    }
    
            
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
